//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int id { get; set; }
        public Nullable<System.DateTime> attend { get; set; }
        public Nullable<System.DateTime> Departure { get; set; }
        public Nullable<int> employeeId { get; set; }
    
        public virtual EmpolyeePersonalData EmpolyeePersonalData { get; set; }
    }
}
