//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authentication
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<bool> canAdd { get; set; }
        public Nullable<bool> canUpdate { get; set; }
        public Nullable<bool> canDelete { get; set; }
        public Nullable<bool> canView { get; set; }
        public Nullable<int> groupId { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
