//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeWorkData
    {
        public int id { get; set; }
        public Nullable<System.DateTime> workDate { get; set; }
        public Nullable<decimal> sallery { get; set; }
        public Nullable<System.DateTime> attandanceDate { get; set; }
        public Nullable<System.DateTime> outDate { get; set; }
        public Nullable<int> employeeID { get; set; }
    
        public virtual EmpolyeePersonalData EmpolyeePersonalData { get; set; }
    }
}
