//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HREntities : DbContext
    {
        public HREntities()
            : base("name=HREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Attendance> Attendance { get; set; }
        public virtual DbSet<Authentication> Authentication { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<EmployeeWorkData> EmployeeWorkData { get; set; }
        public virtual DbSet<EmpolyeePersonalData> EmpolyeePersonalData { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<Hours> Hours { get; set; }
        public virtual DbSet<OfficialVacations> OfficialVacations { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<WeekalyHoliday> WeekalyHoliday { get; set; }
    }
}
